name: test

on: [ push, pull_request ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala: ["2.11.12", "2.12.15", "2.13.7"]

    steps:
    - uses: actions/checkout@v2
    - uses: olafurpg/setup-scala@v12
      with:
        java-version: adopt@1.8
    - name: Run tests
      run: sbt test
      env:
        SCALA_VERSION: ${{ matrix.scala }}
